export const meta = {
  name: 'roster-lab-swarm',
  description: 'Empirical experiment campaign: 16 real-measurement charters across every ROSTER subsystem + skeptic verification of change-proposing findings',
  phases: [
    { title: 'Experiments', detail: '16 charters — real models, real servers, real processes' },
    { title: 'Verify', detail: 'skeptics attack methodology + reproduce cheap' },
  ],
}

const COMMON = `You are one experiment agent in a swarm empirically hardening ROSTER — a local-first MCP tool router (monorepo at /Users/mo/Downloads/roster; pnpm installed; packages built to dist/). Your job: RUN REAL EXPERIMENTS and report measured truth. Context for the bar you are held to: live measurement previously exposed that the (cos+1)/2 cosine mapping silently turned nominal 70/30 hybrid fusion into ~10/90 — a truth no code review or mocked test found. Find truths like that in your charter's area.

REAL-ONLY LAW (owner's direct order — binding): real ONNX inference via transformers.js (actual MiniLM/Gemma models), real MCP servers spawned via npx, real SQLite database files, real OS processes and real kill signals, real CLI modules operating on real files. NO mock embedding providers, NO synthetic stand-in vectors for retrieval conclusions, NO simulated "would-have" numbers. The repo's unit suite already covers mocked logic — your job is precisely the unmocked reality.

Ground rules (binding):
1. NEVER modify existing files. Create ONLY new files: docs/lab/exp-<slug>*.mjs, docs/lab/results-<slug>.json, docs/lab/notes-<slug>.md, scratch under docs/lab/tmp-<slug>/ (delete scratch when done). If dist/ imports fail, you may run "pnpm build" (regenerates dist only).
2. Import built packages exactly like docs/verification/dense-live.mjs does (createRequire against packages/cli/package.json, then resolve "@rosterhq/coach" etc). READ that file first, and inspect each package's src/index.ts for the export surface — do not guess API names.
3. Shared fixtures (use them wherever relevant so the swarm's numbers are comparable): docs/lab/corpus.mjs (133 real-world tool cards, TOOLS/TOOL_IDS), docs/lab/needs.mjs (66 ground-truthed needs: {need, style, primary, acceptable}), docs/lab/metrics.mjs (rankedIds, hitAtK, reciprocalRank, mean, percentile, summarize).
4. NO FABRICATED NUMBERS — every number you report must come from code you executed in this run, with raw output saved to docs/lab/results-<slug>.json. If something fails to run, report the failure honestly instead of estimating.
5. Databases: openCoachDb(":memory:") or files under your tmp dir. Anything touching CLI config paths MUST set ROSTER_TEST_HOME to your tmp dir — never the real HOME. Real servers (npx -y @modelcontextprotocol/server-filesystem etc.) sandbox to your tmp dir.
6. Embeddings: real TransformersEmbeddings with MiniLM unless your charter says Gemma (RAM budget: only the gemma charter loads Gemma). Dispose providers when done.
7. Budget: aim ≤ ~25 min of compute; subsample and SAY SO rather than overrun. Siblings run concurrently — keep RAM under ~2GB. Do not run pnpm vitest (not your job).
8. Findings must separate MEASUREMENT (what numbers show) from PROPOSAL (what to change — never change it yourself). Severity: high = user-visible wrongness/crash/trust-claim violation; medium = measurable quality or performance loss; low/info = polish or interesting truth. Include concrete numbers + the results-file path in every evidence string.
9. Write notes-<slug>.md for humans: question, method, numbers (tables), conclusion.
Your final structured output is consumed by an orchestrator — return real data, compact but concrete.`

const FINDINGS_SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['experiments', 'findings', 'surprises', 'artifacts'],
  properties: {
    experiments: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['name', 'question', 'method', 'headline'], properties: {
      name: { type: 'string' }, question: { type: 'string' }, method: { type: 'string' }, headline: { type: 'string', description: 'one sentence with the key measured numbers' } } } },
    findings: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['severity', 'title', 'claim', 'evidence', 'confidence'], properties: {
      severity: { enum: ['high', 'medium', 'low', 'info'] }, title: { type: 'string' }, claim: { type: 'string' }, evidence: { type: 'string' },
      proposed_change: { type: 'string', description: 'omit if no code/doc change is proposed' }, confidence: { enum: ['high', 'medium', 'low'] } } } },
    surprises: { type: 'array', items: { type: 'string' } },
    artifacts: { type: 'array', items: { type: 'string' } },
  },
}

const VERDICT_SCHEMA = {
  type: 'object', additionalProperties: false, required: ['verdict', 'reasoning'],
  properties: { verdict: { enum: ['CONFIRMED', 'ARTIFACT', 'INCONCLUSIVE'] }, reasoning: { type: 'string' }, corrected_claim: { type: 'string' } },
}

const CHARTERS = [
  { slug: 'retrieval-minilm', title: 'Retrieval quality + fusion calibration (MiniLM, real inference)', prompt: `Embed all 133 corpus tool cards ("name\\n<description>" like the serve path) and all 66 needs with REAL MiniLM. Store base vecs in a real CoachStore. Measure: (a) hit@1/hit@5/MRR for lexical-only vs hybrid draftCandidates, overall and per style; (b) weight sweep — since weights are module constants, reimplement ONLY the fusion arithmetic in your script on top of the store's real lexScore/cosScore outputs (state clearly it mirrors store.ts fusion) and sweep lex/cos {1/0, .7/.3, .5/.5, .3/.7, 0/1}; (c) per-draft cosine span distribution (deciles) + abstain rate at the shipped 0.15 threshold; threshold sweep 0→0.4 step 0.05 → hit@5 curve; (d) count needs where hybrid RANKS the best acceptable tool WORSE than lexical-only (regressions). Deliver: is 0.3/0.7 + 0.15-abstain right for MiniLM? Evidence-backed recommendation.` },
  { slug: 'gemma-calibration', title: 'Gemma calibration: spans, threshold, Matryoshka dims (real Gemma)', prompt: `Only agent allowed to load Gemma (already in the HF cache from prior verification; loading it is real inference, ~seconds warm). Serially: (a) embed corpus + needs with correct query/document kinds; hit@1/hit@5/MRR lexical vs hybrid, overall + per style; (b) per-draft cosine span distributions for REAL needs vs NOISE needs (shuffle each need's words; plus 10 gibberish strings) → do Gemma noise spans exceed the 0.15 abstain threshold? Report overlap of the two distributions — this decides whether 0.15 is right for Gemma, which was calibrated on MiniLM only; (c) threshold sweep 0→0.4 step 0.05 → hit@5 + abstain-rate curves; (d) Matryoshka dim study: embed once at native dims, truncate+renormalize to 128/256/512 → hit@5/MRR + span distribution per dim — is 256 the right default? (e) regressions vs lexical as in the minilm charter. Dispose the model when done. This is the highest-stakes charter: the shipped threshold has never been measured against Gemma.` },
  { slug: 'oats-dynamics', title: 'OATS learning dynamics (real MiniLM vectors)', prompt: `All vectors REAL MiniLM embeddings of corpus cards/needs. Measure: (a) sensitivity curve — pick 3 tools with weak base retrieval for their need-family (from a quick hybrid baseline); for N=1..12 recorded successes (fresh store per N, real need embeddings, runOats) plot post-OATS rank of that tool for held-out paraphrase needs of the same family; (b) idempotence/drift — run runOats 30x on unchanged data; L2 delta of adj vector per run (does it converge, oscillate, or drift?); (c) destructive interference — one tool succeeding for TWO orthogonal need-families (e.g. fetch used for scraping AND for API polling): post-OATS rank per family vs single-family baseline; (d) negatives — seed failures for a confusable WRONG tool (β push-away): does the right tool gain rank, does the wrong tool fall, any collateral damage on unrelated needs (hit@5 delta on the full needs set)?; (e) poisoning — 1..5 mislabeled successes on a wrong tool: rank damage + how many correct outcomes to recover; (f) do post-OATS cosine spans clear the 0.15 abstain gate after realistic light usage (3-6 outcomes on 2-3 tools)?` },
  { slug: 'lexical-edges', title: 'Lexical/FTS5 edge cases, stopword pollution, query-safety fuzz', prompt: `Real CoachStore + corpus. (a) tokenizer reality: for 15 needs, generate snake_case/camelCase/hyphenated/pluralized/verb-form variants → rank deltas of the ground-truth tool (does "search files" match search_files? "committing" vs commit?); (b) stopword pollution: quantify how often {for,the,a,in,to,my,that} matches alone drive a wrong-source tool into top-5 (the fs-tool-#2-for-a-memory-need incident was this class); measure top-5 contamination rate across all 66 needs; (c) query-safety fuzz: 200+ hostile needs through draftCandidates — double/single quotes, FTS5 operators (AND OR NOT NEAR *, ^, parens, colons), unicode, emoji, 10KB string, empty, whitespace-only, newlines, null chars — ANY throw/SQL error = high finding with exact input; (d) lexicalSearch normalization at edges: 1 candidate, all-equal ranks (span==0), 2 candidates. Also record: does the sanitizer strip too much (legit hyphenated terms losing signal)?` },
  { slug: 'token-economics', title: 'Receipt/marketing numbers measured for real + trim-depth study', prompt: `THE public numbers — measure, never model, where reality is reachable. (a) spawn REAL fs + memory servers via npx (sandbox tmp), capture their actual tools/list JSON; compute tokens (estimateTokensFromChars from @rosterhq/shared) for: full direct tool list vs roster transparent list vs a 5-card draft (real draftCandidates output through the real card builder in @rosterhq/router if importable — read its index) → absolute tokens + % saved; (b) same arithmetic for the 133-tool corpus roster (a realistic power-user setup): full list vs 5-card draft; (c) cross-check estimateTokensFromChars honesty: load a REAL tokenizer via the repo's existing @huggingface/transformers dependency (AutoTokenizer for MiniLM) and count real tokens for the same payloads; report the heuristic's bias % (note BPE families differ from Claude's tokenizer — state as caveat, no fabricated Claude numbers); (d) trimSchema depth study on the REAL schemas captured in (a) plus 3 pathological synthetics (6-deep nesting, 200 properties, anyOf forest): tokens per card at each trim depth + which semantically load-bearing keys (required/enum/default) get dropped. Deliver the honest headline: "N tools, X tokens direct vs Y via draft (−P%)" with results-file trace.` },
  { slug: 'proxy-tax', title: 'Latency + storage: the honest cost of the middleman', prompt: `All timings on real machinery, hrtime, warmup runs excluded, report p50/p95 over ≥100 iterations. (a) draftCandidates latency at roster sizes 10/50/133/500 (synthesize extras by suffixing corpus entries; vectors REAL MiniLM, embedded once) — lexical-only vs hybrid-with-cached-vecs; (b) CALL_TOOL overhead: 50 read_text_file calls direct MCP client→real fs server vs through the real rosterServer (transparent mode AND five-mode) — added ms p50/p95 (wire rosterServer exactly as packages/cli serve does — read that code); (c) cold boot→first-draft time with 133 tools (model warm in cache; exclude download, say so); (d) DB growth: file size after 1k and 10k recordOutcome calls + vecs; draft latency at 10k outcomes (degradation?); recomputeRatings + runOats wall time at 10k. Deliver the honest proxy-tax table for docs.` },
  { slug: 'concurrency-stress', title: 'Multi-process reality: contention, crashes, torn writes', prompt: `We publicly claim multi-process safety — attack it with REAL processes (child_process.spawn, real DB file in tmp). (a) 8 concurrent node processes × 200 mixed ops each (upsertCapabilities/recordOutcome/draftCandidates/recomputeRatings) on ONE shared DB → count thrown errors by code (SQLITE_BUSY? SNAPSHOT?), then PRAGMA integrity_check; (b) two processes racing full sync cycles (upsert+pruneMissing with keepSeenSince like serve boot does) with overlapping-but-different rosters → any server's capabilities lost?; (c) crash-safety: kill -9 a writer mid-transaction, 20 rounds → integrity_check + WAL recovery each round; (d) torn config writes: 4 processes × 100 saveConfig calls (via @rosterhq/cli internals, ROSTER_TEST_HOME) to the same roster.json → after every write the file must parse as valid JSON (reader loop polling) — any torn read = high. Report exact error counts; zero-error claims need the run trace in results.` },
  { slug: 'sync-eject-fuzz', title: 'Byte-for-byte eject under fuzz — the trust surface', prompt: `The public claim: eject restores client configs byte-for-byte. Attack with real files (ROSTER_TEST_HOME=tmp). Read packages/cli/src/{clients,rosterfile,sync,eject}.ts first. (a) 100 generated client configs across ALL 10 registered client formats — valid-but-weird: unicode keys/values, deep env objects, 1MB config, minimal, empty mcpServers, extra unknown top-level keys, mixed indentation, no trailing newline, CRLF — run sync → eject → byte-compare (raw Buffer) to original; ANY mismatch = high with hex diff position; (b) sequence fuzz: 30 random-order sequences of sync/eject/sync-again/config-edited-between → invariants: user's own servers never lost, backups+manifest always sufficient, latest-pointer correct, era archiving on restore; (c) tamper: corrupt one byte of a backup → eject must refuse safely (integrity check), not restore garbage; (d) crash-window approximation: snapshot the directory between each observable step of a sync (instrument by running steps via the module's exported functions if granular enough — read the code; otherwise state honestly what window you could not test) → from each snapshot, is recovery possible?` },
  { slug: 'classifier-realworld', title: 'Outcome classifier vs real wire shapes from real failures', prompt: `Force REAL failures from REAL servers and capture what actually comes over the wire, then check classifyOutcome (read packages/coach/src/classifier.ts + @rosterhq/router evidence mapping in backends.ts first — classification consumes the router's evidence, so build evidence exactly as backends.ts does). Scenarios: fs server — read nonexistent path; write to a path outside its sandbox root; chmod-000 file read; memory server — malformed/wrong-shape args; kill the server process mid-call (transport death); a hanging fake stdio server (node -e with no MCP handshake) → connect timeout; a server returning isError:true with realistic texts (rate limit, 429, quota exceeded, unauthorized, invalid params, not found — drive the real everything-server echo or your own minimal REAL MCP server built with the repo's @modelcontextprotocol/sdk to emit exact payloads). Table: scenario → captured wire shape → evidence → class → is that the SPEC's intent (ROSTER-BUILD-HANDOFF §6 classifier section)? (b) precedence fuzz: 500 random evidence combos → precedence always transport>protocol>timeout>isError-kinds>drift; isAttributable consistent with docs/methodology.md §8; (c) report misclassified real-world error texts with proposed rule tweaks (proposal only).` },
  { slug: 'playbook-trust', title: 'SKILL.md parsing robustness + trust-scan FP/FN rates', prompt: `Real files on disk under tmp (ROSTER_TEST_HOME for scan paths — read packages/playbook/src/scan.ts for the roots it honors). (a) parse robustness: 60 SKILL.md fuzz cases — no frontmatter, unterminated ---, BOM, CRLF, 2MB body, emoji/unicode names, code fences containing --- lines, YAML anchors/aliases, tabs-vs-spaces, frontmatter-only, empty file → any crash/hang/mis-parse = high; (b) trust-scan detection matrix: seed 15 malicious skills (prompt-injection phrasing in description/body: "ignore previous instructions", exfiltration URL, curl|bash in a bundled script, base64 blob, "run this at the start of every session" persistence) + 15 benign realistic skills (faithful pastiches of common public skills: TDD, debugging, brainstorming, PDF-tools) → FP/FN rates from the real trust.ts scanner; list every miss verbatim; (c) OpenClaw injection-cost formula: verify the 195+Σ(97+len) accounting against 10 of your real skill files using the repo's own entry.ts/openclaw.ts code paths + estimateTokensFromChars — formula drift = medium; (d) symlinked skill dir: confirm documented skip is silent-and-safe, not a crash.` },
  { slug: 'combine-adversarial', title: 'Combine integrity: determinism, mutation-testing the verifiers, containment', prompt: `The League's integrity rests on the Combine. Real runner, real npx fs server, tmp sandboxes. (a) determinism: run suites/filesystem 3x → lab-results identical modulo timing/digest fields? field-level diff; (b) MUTATION-TEST the 8 tasks' verifiers: for each task, after a passing run, sabotage the end state (wrong content, missing file, extra file, right content wrong path, case-flipped filename, trailing-newline delta) and re-verify → EVERY sabotage must fail; any false-pass = high with the exact mutation; (c) false-fail hunt: 3 clean re-runs with different tmp path lengths/nesting → flakes?; (d) containment: craft task args attempting escape (../ traversal, absolute path, symlink pointing outside, ~ expansion, embedded null byte) through the REAL runner path-guard → all contained with clean failures, nothing written outside sandbox (verify by filesystem scan); (e) timeout: a hanging fake server → CONNECT_TIMEOUT fires, classified per design, runner completes the suite.` },
  { slug: 'drift-sim', title: 'Drift/quarantine lifecycle vs spec over simulated server evolution', prompt: `One real store, real DB file. Where dwell logic reads clock time, manipulating timestamp COLUMNS in your own test DB is allowed (state where you did); do not modify source. Simulate 30 virtual days of one server evolving — day events: benign description tweak; schema field added; full signature change; flapping A→B→A within the 24h dwell; tool removed then re-added later; 3 tools changing the same day. After each event run the real upsert path and assert against ROSTER-BUILD-HANDOFF's drift section + docs/methodology.md §6: drift_event rows created; quarantine flips exactly when spec says; 24h dwell honored (not cleared early); stable-re-sight auto-clear works; quarantined tools excluded from draftCandidates but rated-fallback behavior as designed; unquarantine path (CLI or store call) clears correctly; ratings continuity across benign vs signature drift. Any spec/code divergence = medium+, with the exact event sequence to reproduce.` },
  { slug: 'embed-torture', title: 'Embedding provider torture (real MiniLM, real ONNX lifecycle)', prompt: `Real TransformersEmbeddings + MiniLM only. (a) queue serialization: 50 concurrent embed() via Promise.all — all resolve; identical text → bitwise-identical vector across calls?; interleaved batches uncorrupted (spot-check against serial reference vectors); (b) dispose-during-flight: launch 20 embeds, dispose() mid-stream → in-flight calls settle cleanly (resolve or clean rejection), zero unhandledRejection events (hook process), post-dispose embed rejects with a clear error; (c) re-warm cycles ×5 (provider → embed corpus → dispose → new provider): RSS after each full cycle (leak trend line) — this tests the recent real-dispose fix's claim (~300MB reclaim); report RSS numbers before/during/after; (d) input torture: "", 1 char, 100KB text, emoji-only, RTL text, \\u0000 inside, 500 identical texts in one call → vector or clean error; scan EVERY output vector this whole charter for NaN/Inf = high if found; (e) chunked-batch equivalence: 133 corpus texts one-by-one vs batch-of-16 chunks (the serve path) → bitwise same? timing per text both ways.` },
  { slug: 'e2e-realism', title: 'Day-in-the-life: 40-call agent session through the real router, learning measured', prompt: `The closest thing to production: real rosterServer (wire it exactly as packages/cli/src/serve.ts does — read it), real fs + memory backends via npx, REAL MiniLM embedder for need embeddings, real MCP client over the SDK's InMemory or stdio transport. Script a 40-call session mimicking a working agent: ~60% well-phrased needs (use needs.mjs phrasings for fs/memory), 20% vague, 10% wrong-tool-then-corrected-retry (should produce soft-fail marking), 10% genuine failures (bad args). Flow per step: DRAFT_TOOL(need) → pick from draft like an agent would → CALL_TOOL with draft_id → outcome recorded by the router itself. Mid-session, run the real maintenance (recomputeRatings + runOats). Measure: (a) rank-of-used-tool in drafts, first 10 calls vs last 10 (does the session LEARN?); (b) Sixth Man: how often suggestions fire, are they well-formed namespaced ids, and confirm zero side effects beyond the suggestion text (suggest-only law); (c) draft_id attribution: query the DB — every outcome row attributed to the right draft/suggestion rows?; (d) protocol fidelity spot-checks: force one backend McpError → surfaces to the client exactly as direct connection would (compare shapes); isError payload byte-shape preserved. Report per-call table in results JSON.` },
  { slug: 'ratings-math', title: 'Ratings math property-tested against an independent reference', prompt: `Real repo code under test; your reference implementations written fresh from the cited formulas (this is the one sanctioned reimplementation — for cross-checking only). (a) wilsonLowerBound: property-test vs your independent implementation of the Evan Miller formula over 5000 random (n∈0..10000, s≤n) incl. edges n=0, n=1, s=0, s=n → max abs diff; monotonicity: s+1 at fixed n never lowers LB; same p̂ at larger n raises LB; output always in [0,1]; (b) recomputeRatings on seeded synthetic outcome sets in a real store: soft_fail + explored excluded (verify by construction), class weighting/wilson inputs match a hand-computed table for 5 constructed cases; (c) rated-fallback: gibberish need (zero FTS hits) at roster sizes 5 and 133 → drafts non-empty, ordered by rating, deterministic across 10 repeats (tie-break stability); (d) percentile + latencyBucket edges: empty, single element, all-ties, boundary values exactly on bucket edges. Exact-math bugs = high (Wilson LB backs public named scores).` },
  { slug: 'identity-fuzz', title: 'Namespacing collisions, backend registry, schema-trim torture', prompt: `Misattribution silently corrupts ratings — hunt collisions with real code. (a) namespacedId/parseNamespacedId round-trip fuzz: 1000 (source,name) pairs — unicode, spaces, dots, dashes, leading digits, 200-char, "__" inside the NAME, mixed case → every pair round-trips or cleanly rejects; then COLLISION HUNT: generate pairs designed so sanitization could map distinct (source,name) to the same id (e.g. "a_b"/"c" vs "a"/"b_c" patterns per the sanitizer's rules — read namespacing.ts first) → any two distinct inputs with equal id = HIGH (outcome/rating misattribution); (b) BackendManager registry: register real InMemory backends named to collide post-sanitization ("my-server", "my_server", "MY SERVER") plus one literally named "skill" → suffixing correct, lookup returns the right backend for every tool, reserved word honored; (c) trimSchema torture: cyclic $ref, 50-deep nesting, 500 properties, 1000-entry enum, anyOf-of-anyOfs, boolean schemas (true/false), null → terminates <100ms each, valid JSON out, no throw; (d) the Ajv args_compatible path (read rosterServer.ts): $schema draft-07 vs 2020-12 vs bogus URI, plus the pathological schemas from (c) → validates or cleanly bypasses per design; the server loop must never crash — any throw = high.` },
]

const verifyPrompt = (f, slug, lens) => `You are a skeptical verifier. An experiment agent (charter "${slug}") produced this change-proposing finding:
TITLE: ${f.title}
SEVERITY: ${f.severity} (confidence ${f.confidence})
CLAIM: ${f.claim}
EVIDENCE: ${f.evidence}
PROPOSED CHANGE: ${f.proposed_change}

Your job is to try to REFUTE it. ${lens === 0
  ? 'Lens: methodology + ground truth. Read docs/lab/results-' + slug + '.json, notes-' + slug + '.md and the exp-' + slug + '*.mjs script; check the numbers are actually in the results file, the sample size supports the claim, the ground truth in docs/lab/needs.mjs is itself right for the needs involved (it is human judgment and fallible), and no confound explains it (model nondeterminism, caching, machine load for latency claims, corpus descriptions being one-liners).'
  : 'Lens: independent reproduction. Re-run the smallest REAL experiment that tests the claim directly (real inference/processes, no mocks — this is binding), in your own scratch dir docs/lab/tmp-verify-' + slug + '-' + lens + '/ (clean up after). If reproduction would exceed ~5 minutes of compute, verify the strongest cheap proxy and say so.'}
Repo is READ-ONLY for you except your own scratch dir. Verdict: CONFIRMED only if the measurement is real AND the causal story holds; ARTIFACT if methodology/ground-truth/confound explains it away (say which, and give corrected_claim); INCONCLUSIVE if not cheaply verifiable.`

log('Launching 16 experiment charters — real models, real servers, real processes. Verifiers spawn per change-proposing finding as each charter lands.')

const campaign = await pipeline(
  CHARTERS,
  (c) => agent(
    COMMON + '\n\n## YOUR CHARTER: ' + c.title + '\nYour slug: ' + c.slug + ' (files: docs/lab/exp-' + c.slug + '*.mjs, results-' + c.slug + '.json, notes-' + c.slug + '.md, scratch tmp-' + c.slug + '/).\n\n' + c.prompt,
    { label: 'exp:' + c.slug, phase: 'Experiments', schema: FINDINGS_SCHEMA },
  ),
  (res, c) => {
    if (!res) { log('charter ' + c.slug + ' returned nothing (skipped or died)'); return { slug: c.slug, ok: false } }
    const eligible = res.findings.filter((f) => f.proposed_change && (f.severity === 'high' || f.severity === 'medium'))
    const capped = eligible.slice(0, 8)
    if (eligible.length > 8) log('verify capped at 8/' + eligible.length + ' findings for ' + c.slug)
    log(c.slug + ': ' + res.experiments.length + ' experiments, ' + res.findings.length + ' findings (' + capped.length + ' to verify)')
    return parallel(
      capped.flatMap((f) => {
        const lenses = f.severity === 'high' ? [0, 1] : [0]
        return lenses.map((lens) => () =>
          agent(verifyPrompt(f, c.slug, lens), { label: 'verify:' + c.slug + ':' + f.title.slice(0, 28), phase: 'Verify', schema: VERDICT_SCHEMA })
            .then((v) => ({ title: f.title, severity: f.severity, lens, verdict: v })))
      }),
    ).then((verdicts) => ({ slug: c.slug, ok: true, report: res, verdicts: verdicts.filter(Boolean) }))
  },
)

const done = campaign.filter(Boolean)
log('Campaign complete: ' + done.filter((r) => r.ok).length + '/' + CHARTERS.length + ' charters reported.')
return { campaign: done }