import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const name = "@npmmo/roster";
const version = "0.0.2";
const expectedSha = "3f42c2d5c0648b9c3a64fbb7eadedf27dd507f1f9d6a0e8731d10fcc385895a0";
const directory = path.resolve(process.argv[2]);
const response = await fetch("https://registry.npmjs.org/@npmmo%2froster", { redirect: "error", signal: AbortSignal.timeout(60_000) });
assert.equal(response.status, 200, `approved public release unavailable: HTTP ${response.status}`);
const packument = await response.json();
const manifest = packument.versions?.[version];
assert.equal(packument["dist-tags"]?.latest, version);
assert.equal(manifest?.name, name);
assert.equal(manifest?.version, version);
const url = new URL(manifest.dist.tarball);
assert.equal(url.protocol, "https:");
assert.equal(url.hostname, "registry.npmjs.org");
const download = await fetch(url, { redirect: "error", signal: AbortSignal.timeout(60_000) });
assert.equal(download.status, 200);
const archive = Buffer.from(await download.arrayBuffer());
const sha256 = crypto.createHash("sha256").update(archive).digest("hex");
const integrity = `sha512-${crypto.createHash("sha512").update(archive).digest("base64")}`;
assert.equal(sha256, expectedSha);
assert.equal(integrity, manifest.dist.integrity);
const record = { name, version, latest: packument["dist-tags"].latest, sha256, integrity, tarball: url.href, publishedAt: packument.time?.[version], publisher: manifest._npmUser?.name, checkedAt: new Date().toISOString() };
fs.mkdirSync(directory, { recursive: true });
fs.writeFileSync(path.join(directory, "npmmo-roster-0.0.2.tgz"), archive);
fs.writeFileSync(path.join(directory, "public-identity.json"), JSON.stringify(record, null, 2));
console.log(JSON.stringify(record, null, 2));
