/**
 * The score, synthesised.
 *
 * Everything you hear in the film is generated by this file: no samples, no
 * library, no licence to worry about. It reads the cue table straight out of
 * `src/audio/cues.ts` (transpiled on the fly by tsx-free hand-parsing is fragile,
 * so we import the compiled-by-esbuild module through Node's TS support), then
 * renders one 44.1 kHz stereo WAV into `public/audio/`.
 *
 * Design notes:
 *  · A quiet bed of two detuned pads plus filtered air runs the whole film, so
 *    the sound never fully drops out between cues.
 *  · Every one-shot is a small physical model — an exciter through a decaying
 *    resonator — rather than a synth preset, which is why the lineup impacts and
 *    the identity hit share a family resemblance.
 *  · Peak-normalised to −1.5 dBFS with a soft knee, so nothing clips and the
 *    film still works muted.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { CUES, SAMPLE_RATE, SCORE_SECONDS, SCORE_FILE } from "../src/audio/cues.ts";

const FPS = 60;
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const outPath = path.join(root, "public", SCORE_FILE);

const sr = SAMPLE_RATE;
const total = Math.ceil(SCORE_SECONDS * sr);
const left = new Float64Array(total);
const right = new Float64Array(total);

/* ── deterministic noise ─────────────────────────────────────────────────── */

let noiseState = 0x2f6e2b1 >>> 0;
function rnd() {
  noiseState = (noiseState + 0x6d2b79f5) >>> 0;
  let t = noiseState;
  t = Math.imul(t ^ (t >>> 15), t | 1);
  t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
}
const noise = () => rnd() * 2 - 1;

/* ── helpers ─────────────────────────────────────────────────────────────── */

const frameToSample = (f) => Math.round((f / FPS) * sr);
const semis = (n) => 2 ** (n / 12);

function add(i, l, r) {
  if (i < 0 || i >= total) return;
  left[i] += l;
  right[i] += r;
}

/** One-pole low-pass, stateful per call site. */
function makeLowpass(cut) {
  const a = Math.exp((-2 * Math.PI * cut) / sr);
  let y = 0;
  return (x) => {
    y = x * (1 - a) + y * a;
    return y;
  };
}

/** One-pole high-pass. */
function makeHighpass(cut) {
  const lp = makeLowpass(cut);
  return (x) => x - lp(x);
}

/** Exponential decay envelope. */
const decay = (t, tau) => Math.exp(-t / tau);

/** Attack/decay envelope in seconds. */
function ad(t, attack, release) {
  if (t < 0) return 0;
  if (t < attack) return t / attack;
  return decay(t - attack, release);
}

/**
 * Render a mono generator into the buffer with a stereo position.
 * `gen(t, i)` returns a sample for local time t seconds.
 */
function render(startFrame, seconds, gen, gain = 1, pan = 0) {
  const start = frameToSample(startFrame);
  const n = Math.ceil(seconds * sr);
  const gl = gain * Math.cos(((pan + 1) * Math.PI) / 4);
  const gr = gain * Math.sin(((pan + 1) * Math.PI) / 4);
  for (let i = 0; i < n; i++) {
    const t = i / sr;
    const s = gen(t, i);
    add(start + i, s * gl, s * gr);
  }
}

/* ── voices ──────────────────────────────────────────────────────────────── */

/** The bed: two slowly beating pads plus a whisper of filtered air. */
function ambientBed(startFrame, lengthFrames, gain) {
  const seconds = lengthFrames / FPS;
  const lp = makeLowpass(900);
  const hp = makeHighpass(120);
  const root = 55; // A1
  render(
    startFrame,
    seconds,
    (t) => {
      // Long swell in and out so the film never starts or ends on a hard edge.
      const env = Math.min(1, t / 3.2) * Math.min(1, Math.max(0, seconds - t) / 3.6);
      // A quiet minor-ninth pad: root, fifth, ninth. Detuned by fractions of a Hz.
      const pad =
        Math.sin(2 * Math.PI * root * t) * 0.5 +
        Math.sin(2 * Math.PI * (root * 1.4983) * t + 1.1) * 0.32 +
        Math.sin(2 * Math.PI * (root * 2.2449) * t + 2.3) * 0.2 +
        Math.sin(2 * Math.PI * (root * 4.0 + 0.17) * t + 0.4) * 0.11;
      // Slow amplitude motion, two incommensurate rates so it never loops audibly.
      const motion = 0.72 + 0.18 * Math.sin(t * 0.19) + 0.1 * Math.sin(t * 0.071 + 2.0);
      const air = hp(lp(noise())) * 0.05;
      return (pad * 0.16 * motion + air) * env;
    },
    gain,
    0,
  );
}

/** A key press: a tiny click through a short resonant body. */
function typeTick(startFrame, gain, detune) {
  const f = 1650 * semis(detune);
  const bp = makeLowpass(5200);
  render(
    startFrame,
    0.14,
    (t) => {
      const click = decay(t, 0.0022) * noise();
      const body = Math.sin(2 * Math.PI * f * t) * decay(t, 0.014);
      const thud = Math.sin(2 * Math.PI * 190 * t) * decay(t, 0.03);
      return bp(click * 0.7 + body * 0.34 + thud * 0.22);
    },
    gain * 0.32,
    (detune % 5) / 14,
  );
}

/** Overload: a rising filtered noise band with a low drone underneath. */
function tension(startFrame, lengthFrames, gain) {
  const seconds = lengthFrames / FPS;
  let lp = makeLowpass(300);
  const hp = makeHighpass(90);
  render(
    startFrame,
    seconds,
    (t) => {
      const p = Math.min(1, t / seconds);
      const env = Math.min(1, t / 1.4) * Math.min(1, Math.max(0, seconds - t) / 1.1);
      // The band opens from 300 Hz to ~2.6 kHz across the scene.
      lp = makeLowpass(300 + p * p * 2300);
      const band = hp(lp(noise())) * (0.06 + p * 0.1);
      const drone =
        (Math.sin(2 * Math.PI * 41 * t) * 0.5 + Math.sin(2 * Math.PI * 61.7 * t + 0.7) * 0.3) *
        (0.06 + p * 0.08);
      // A slow tremolo that speeds up — pressure without a ticking clock.
      const trem = 0.82 + 0.18 * Math.sin(2 * Math.PI * (0.8 + p * 2.4) * t);
      return (band + drone) * env * trem;
    },
    gain,
    0,
  );
}

/** The clean shift: a downward filtered sweep landing on a soft consonance. */
function shift(startFrame, gain, detune = 0) {
  render(
    startFrame,
    1.9,
    (t) => {
      const sweepF = 1400 * Math.exp(-t * 3.6) + 180;
      const sweep = Math.sin(2 * Math.PI * sweepF * t) * decay(t, 0.22) * 0.4;
      const landing =
        (Math.sin(2 * Math.PI * 220 * semis(detune) * t) * 0.5 +
          Math.sin(2 * Math.PI * 330 * semis(detune) * t) * 0.3 +
          Math.sin(2 * Math.PI * 440 * semis(detune) * t) * 0.18) *
        ad(t - 0.12, 0.02, 0.55) *
        0.34;
      return sweep + landing;
    },
    gain * 0.5,
    0,
  );
}

/** The scan: a slow band-passed noise sweep travelling across the stereo field. */
function scan(startFrame, lengthFrames, gain, detune = 0) {
  const seconds = lengthFrames / FPS;
  let lp = makeLowpass(1000);
  let hp = makeHighpass(400);
  const start = frameToSample(startFrame);
  const n = Math.ceil(seconds * sr);
  for (let i = 0; i < n; i++) {
    const t = i / sr;
    const p = t / seconds;
    const centre = (700 + p * 2600) * semis(detune);
    lp = makeLowpass(centre * 1.5);
    hp = makeHighpass(centre * 0.62);
    const env = Math.sin(Math.PI * Math.min(1, p)) ** 1.3;
    const s = hp(lp(noise())) * env * 0.2;
    const tone = Math.sin(2 * Math.PI * centre * t) * env * 0.03;
    // pan travels left → right with the plane
    const pan = -0.75 + p * 1.5;
    const gl = gain * Math.cos(((pan + 1) * Math.PI) / 4);
    const gr = gain * Math.sin(((pan + 1) * Math.PI) / 4);
    add(start + i, (s + tone) * gl, (s + tone) * gr);
  }
}

/** A rejection: brittle granular fragments falling. */
function fragment(startFrame, gain, detune = 0) {
  const grains = 13;
  for (let g = 0; g < grains; g++) {
    const at = startFrame + g * 2.6 + rnd() * 3;
    const f = (900 + rnd() * 1700) * semis(detune);
    const pan = (rnd() - 0.5) * 1.3;
    render(
      at,
      0.2,
      (t) => Math.sin(2 * Math.PI * f * t) * decay(t, 0.018 + rnd() * 0.006) * (0.5 + rnd() * 0.5),
      gain * 0.12,
      pan,
    );
  }
  // the settle: a low, soft landing under the grains
  render(
    startFrame + 22,
    0.9,
    (t) => Math.sin(2 * Math.PI * 78 * semis(detune) * t) * ad(t, 0.01, 0.2) * 0.5,
    gain * 0.3,
    0,
  );
}

/** A lineup lock: a soft low impact with a bell partial on top. */
function impact(startFrame, gain, detune = 0) {
  const root = 88 * semis(detune);
  render(
    startFrame,
    1.5,
    (t) => {
      const thump = Math.sin(2 * Math.PI * (root * Math.exp(-t * 9) + root * 0.72) * t) * decay(t, 0.13);
      const bell =
        (Math.sin(2 * Math.PI * root * 5.42 * t) * 0.4 + Math.sin(2 * Math.PI * root * 8.1 * t) * 0.22) *
        decay(t, 0.28);
      const air = noise() * decay(t, 0.008) * 0.2;
      return thump * 0.7 + bell * 0.2 + air;
    },
    gain * 0.42,
    detune / 24,
  );
}

/** A request: a short rising blip. */
function request(startFrame, gain, detune = 0) {
  render(
    startFrame,
    0.6,
    (t) => {
      const f = 420 * semis(detune) * (1 + t * 2.4);
      return Math.sin(2 * Math.PI * f * t) * ad(t, 0.008, 0.11) * 0.5;
    },
    gain * 0.32,
    -0.4,
  );
}

/** A return: the same gesture inverted, warmer, arriving from the other side. */
function returnBlip(startFrame, gain) {
  render(
    startFrame,
    0.9,
    (t) => {
      const f = 900 * Math.exp(-t * 2.1) + 260;
      const tone = Math.sin(2 * Math.PI * f * t) * ad(t, 0.01, 0.2);
      const fifth = Math.sin(2 * Math.PI * f * 1.5 * t) * ad(t, 0.02, 0.16) * 0.4;
      return (tone + fifth) * 0.44;
    },
    gain * 0.34,
    0.42,
  );
}

/** A hard failure: restrained, short, and low. One wobble, no glitch. */
function failure(startFrame, gain) {
  render(
    startFrame,
    1.1,
    (t) => {
      const f = 132 * (1 - t * 0.42);
      const core = Math.sin(2 * Math.PI * f * t);
      // gentle waveshaping — audible strain, not distortion for its own sake
      const shaped = Math.tanh(core * 2.6) * 0.5;
      const wobble = Math.sin(2 * Math.PI * 5.5 * t) * 0.3 + 0.7;
      const grit = noise() * decay(t, 0.02) * 0.18;
      return (shaped * wobble + grit) * ad(t, 0.006, 0.26);
    },
    gain * 0.34,
    0.2,
  );
}

/** The Sixth Man rising: an ascending minor triad, unhurried. */
function sixthMan(startFrame, gain) {
  const notes = [294, 349.2, 440];
  notes.forEach((f, i) => {
    render(
      startFrame + i * 7,
      1.4,
      (t) =>
        (Math.sin(2 * Math.PI * f * t) * 0.6 + Math.sin(2 * Math.PI * f * 2 * t) * 0.16) *
        ad(t, 0.02, 0.3),
      gain * 0.2,
      -0.2 + i * 0.2,
    );
  });
}

/** The identity: a broad low impact under a sustained open chord. */
function identity(startFrame, gain) {
  render(
    startFrame,
    2.0,
    (t) => {
      const sub = Math.sin(2 * Math.PI * (55 * Math.exp(-t * 6) + 44) * t) * decay(t, 0.4);
      const air = noise() * decay(t, 0.012) * 0.3;
      return sub * 0.8 + air;
    },
    gain * 0.5,
    0,
  );
  // the chord that holds under the wordmark: A, E, C#, E — open and unresolved-warm
  const chord = [110, 164.8, 275, 329.6];
  chord.forEach((f, i) => {
    render(
      startFrame + 4 + i * 3,
      4.6,
      (t) =>
        (Math.sin(2 * Math.PI * f * t) * 0.5 + Math.sin(2 * Math.PI * f * 2.002 * t + 0.6) * 0.16) *
        ad(t, 0.35, 1.9),
      gain * 0.14,
      (i - 1.5) * 0.28,
    );
  });
}

/* ── render the cue table ────────────────────────────────────────────────── */

const DISPATCH = {
  ambient: (c) => ambientBed(c.frame, c.length ?? 600, c.gain ?? 1),
  type: (c) => typeTick(c.frame, c.gain ?? 1, c.detune ?? 0),
  tension: (c) => tension(c.frame, c.length ?? 300, c.gain ?? 1),
  shift: (c) => shift(c.frame, c.gain ?? 1, c.detune ?? 0),
  scan: (c) => scan(c.frame, c.length ?? 160, c.gain ?? 1, c.detune ?? 0),
  fragment: (c) => fragment(c.frame, c.gain ?? 1, c.detune ?? 0),
  impact: (c) => impact(c.frame, c.gain ?? 1, c.detune ?? 0),
  request: (c) => request(c.frame, c.gain ?? 1, c.detune ?? 0),
  return: (c) => returnBlip(c.frame, c.gain ?? 1),
  failure: (c) => failure(c.frame, c.gain ?? 1),
  sixth: (c) => sixthMan(c.frame, c.gain ?? 1),
  identity: (c) => identity(c.frame, c.gain ?? 1),
};

for (const cue of CUES) {
  const fn = DISPATCH[cue.kind];
  if (!fn) throw new Error(`no synth for cue kind "${cue.kind}"`);
  fn(cue);
}

/* ── master: soft knee, peak normalise, dither-free 16-bit ───────────────── */

// Soft clip well below 1.0 so the limiter shapes rather than squashes.
const knee = (x) => Math.tanh(x * 0.86) / Math.tanh(0.86);

let peak = 0;
for (let i = 0; i < total; i++) {
  left[i] = knee(left[i]);
  right[i] = knee(right[i]);
  peak = Math.max(peak, Math.abs(left[i]), Math.abs(right[i]));
}
if (peak === 0) throw new Error("score rendered silence");

const targetPeak = 10 ** (-1.5 / 20); // −1.5 dBFS
const norm = targetPeak / peak;

// 30 ms fades on both ends so the file itself can never click.
const fadeSamples = Math.round(0.03 * sr);

const pcm = Buffer.alloc(total * 4);
for (let i = 0; i < total; i++) {
  let edge = 1;
  if (i < fadeSamples) edge = i / fadeSamples;
  else if (i > total - fadeSamples) edge = Math.max(0, (total - i) / fadeSamples);
  const l = Math.max(-1, Math.min(1, left[i] * norm * edge));
  const r = Math.max(-1, Math.min(1, right[i] * norm * edge));
  pcm.writeInt16LE(Math.round(l * 32767), i * 4);
  pcm.writeInt16LE(Math.round(r * 32767), i * 4 + 2);
}

const header = Buffer.alloc(44);
header.write("RIFF", 0);
header.writeUInt32LE(36 + pcm.length, 4);
header.write("WAVE", 8);
header.write("fmt ", 12);
header.writeUInt32LE(16, 16);
header.writeUInt16LE(1, 20); // PCM
header.writeUInt16LE(2, 22); // stereo
header.writeUInt32LE(sr, 24);
header.writeUInt32LE(sr * 4, 28);
header.writeUInt16LE(4, 32);
header.writeUInt16LE(16, 34);
header.write("data", 36);
header.writeUInt32LE(pcm.length, 40);

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, Buffer.concat([header, pcm]));

const dbfs = (20 * Math.log10(peak * norm)).toFixed(2);
process.stdout.write(
  `audio  ${path.relative(root, outPath)}  ${(SCORE_SECONDS).toFixed(2)}s  ${sr} Hz  stereo 16-bit  peak ${dbfs} dBFS  ${CUES.length} cues\n`,
);
