/**
 * Copy the OFL-licensed font binaries we actually use out of node_modules and
 * into `public/fonts/`, so every render reads fonts from local disk and the
 * film has zero network-loaded assets at render time.
 *
 * Fonts: Inter (SIL OFL 1.1) and JetBrains Mono (SIL OFL 1.1).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const outDir = path.join(root, "public", "fonts");

/** [packageSubpath, destination filename] */
const WANTED = [
  ["@fontsource/inter/files/inter-latin-400-normal.woff2", "Inter-400.woff2"],
  ["@fontsource/inter/files/inter-latin-500-normal.woff2", "Inter-500.woff2"],
  ["@fontsource/inter/files/inter-latin-600-normal.woff2", "Inter-600.woff2"],
  ["@fontsource/inter/files/inter-latin-700-normal.woff2", "Inter-700.woff2"],
  ["@fontsource/jetbrains-mono/files/jetbrains-mono-latin-400-normal.woff2", "JetBrainsMono-400.woff2"],
  ["@fontsource/jetbrains-mono/files/jetbrains-mono-latin-500-normal.woff2", "JetBrainsMono-500.woff2"],
  ["@fontsource/jetbrains-mono/files/jetbrains-mono-latin-700-normal.woff2", "JetBrainsMono-700.woff2"],
];

/** Resolve through the workspace node_modules tree (pnpm nests aggressively). */
function resolveFile(subpath) {
  const candidates = [
    path.join(root, "node_modules", subpath),
    path.join(root, "..", "..", "node_modules", subpath),
  ];
  for (const c of candidates) {
    if (fs.existsSync(c)) return c;
  }
  throw new Error(`font not found: ${subpath}`);
}

fs.mkdirSync(outDir, { recursive: true });
for (const [subpath, dest] of WANTED) {
  fs.copyFileSync(resolveFile(subpath), path.join(outDir, dest));
  process.stdout.write(`fonts  ${dest}\n`);
}

// Ship the licences next to the binaries.
for (const [pkg, dest] of [
  ["@fontsource/inter", "Inter-LICENSE.txt"],
  ["@fontsource/jetbrains-mono", "JetBrainsMono-LICENSE.txt"],
]) {
  for (const name of ["LICENSE", "LICENSE.txt", "LICENSE.md"]) {
    const p = path.join(root, "node_modules", pkg, name);
    if (fs.existsSync(p)) {
      fs.copyFileSync(p, path.join(outDir, dest));
      break;
    }
  }
}
/**
 * Also emit the fonts as base64 data URLs.
 *
 * Loading them over HTTP from `public/` worked for single stills but hung under
 * a 4-way concurrent video render — `delayRender()` for "Loading font
 * RosterSans" never cleared and the whole render aborted before frame 0. Data
 * URLs remove the fetch entirely, so a font load cannot race the static server,
 * and the render stays fully local and deterministic. The .woff2 files stay in
 * `public/fonts` alongside their licences.
 */
const entries = WANTED.map(([subpath, dest]) => {
  const b64 = fs.readFileSync(resolveFile(subpath)).toString("base64");
  const key = dest.replace(".woff2", "").replace("-", "_");
  return `  ${key}: "data:font/woff2;base64,${b64}",`;
});

const module = `/**
 * Font binaries, inlined.
 *
 * GENERATED by \`scripts/install-fonts.mjs\` — do not edit by hand; run
 * \`pnpm fonts\` instead. Inter and JetBrains Mono, both SIL OFL 1.1; the
 * licences ship in \`public/fonts/\`.
 */
export const FONT_DATA = {
${entries.join("\n")}
} as const;
`;
fs.writeFileSync(path.join(root, "src", "design", "fontData.ts"), module);
process.stdout.write(`fonts  → ${path.relative(root, outDir)} + src/design/fontData.ts (${(module.length / 1024).toFixed(0)} KB inlined)\n`);
