import {
  isPreSeason,
  isRankable,
  METHODOLOGY_VERSION,
  MIN_RANKED_SIGNED_N,
  type LeagueRun,
  type LoadedArtifact,
} from "./artifact.js";
import { esc, fmt3, layout, pct1 } from "./html.js";

export interface StandingsEntry {
  artifact: LoadedArtifact;
  run: LeagueRun;
}

const slug = (s: string): string => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export const boxScoreFilename = (run: LeagueRun): string => `box-${slug(run.server)}-${slug(run.suite)}.html`;

const record = (run: LeagueRun): string => `${run.summary.passes}–${run.summary.n - run.summary.passes}`;

/**
 * The number a row is judged by. Methodology: signedWilsonLb is the only
 * figure that may back a NAMED score; with zero signed tasks we display the
 * all-tasks Wilson LB marked ᵁ (unsigned tier) for transparency — it can
 * order the pre-season table but can never mint a rank.
 */
const displayLb = (run: LeagueRun): { value: number; unsigned: boolean } =>
  run.summary.signedN > 0
    ? { value: run.summary.signedWilsonLb, unsigned: false }
    : { value: run.summary.wilsonLb, unsigned: true };

const statusChip = (run: LeagueRun): string => {
  if (isRankable(run)) return `<span class="chip ranked">RANKED</span>`;
  if (isPreSeason(run)) return `<span class="chip pre">PRE-SEASON</span>`;
  return `<span class="chip">UNRANKED · ${run.summary.signedN}/${MIN_RANKED_SIGNED_N} SIGNED</span>`;
};

function standingsRow(entry: StandingsEntry, rank: number | null): string {
  const { run } = entry;
  const lb = displayLb(run);
  return `<tr>
<td class="rk">${rank === null ? "—" : String(rank)}</td>
<td class="teamcell"><a href="${esc(boxScoreFilename(run))}">${esc(run.server)}</a><span class="cat">${esc(run.suite)} v${esc(run.suiteVersion)}</span></td>
<td class="record num">${record(run)}</td>
<td class="num">${pct1(run.summary.passRate)}</td>
<td class="lbcell"><span class="lbval">${fmt3(lb.value)}${lb.unsigned ? "<sup>U</sup>" : ""}</span><span class="lbbar"><i style="width:${Math.round(lb.value * 100)}%"></i></span></td>
<td class="num">${run.summary.signedN}/${run.summary.n}</td>
<td>${statusChip(run)}</td>
</tr>`;
}

export function renderStandings(entries: StandingsEntry[]): string {
  const divisions = new Map<string, StandingsEntry[]>();
  for (const e of entries) {
    const list = divisions.get(e.run.category) ?? [];
    list.push(e);
    divisions.set(e.run.category, list);
  }

  const sections = [...divisions.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([category, rows]) => {
      // Ranked rows first (by signed Wilson LB); the rest ordered by the
      // unsigned-tier LB for readability, forever rank-less until signed.
      const ranked = rows.filter((r) => isRankable(r.run)).sort((a, b) => b.run.summary.signedWilsonLb - a.run.summary.signedWilsonLb);
      const rest = rows.filter((r) => !isRankable(r.run)).sort((a, b) => b.run.summary.wilsonLb - a.run.summary.wilsonLb);
      const body = [
        ...ranked.map((r, i) => standingsRow(r, i + 1)),
        ...rest.map((r) => standingsRow(r, null)),
      ].join("\n");
      const anyPre = rows.some((r) => isPreSeason(r.run));
      return `<section class="division">
<div class="divhead"><h2>${esc(category)} division</h2><span class="tierchip">LAB TIER · CONTROLLED SUITES</span></div>
<div class="tablewrap">
<table class="standings">
<thead><tr><th>RK</th><th>Server</th><th>W–L</th><th>Win%</th><th>Wilson LB</th><th>Signed</th><th>Status</th></tr></thead>
<tbody>
${body}
</tbody>
</table>
</div>
<p class="tablefoot"><sup>U</sup> = all-tasks Wilson lower bound (unsigned tier) — shown for transparency, ineligible to mint a rank. Ranked placement requires ≥${MIN_RANKED_SIGNED_N} human-signed tasks.${anyPre ? " Named standings unlock at the first human signing (methodology §4)." : ""}</p>
</section>`;
    })
    .join("\n");

  const body = `<header>
<div class="brandrow"><span class="wordmark">R<b>O</b>STER</span><span class="season">SEASON 0 · <b>PRE-SEASON</b></span></div>
<h1 class="masthead">The League<span class="dot">.</span></h1>
<p class="tag">Public standings for MCP servers. Measured in the open, reproducible by anyone, certified by humans.</p>
<ul class="creed">
<li>Wilson lower bound, never bare averages</li>
<li>n shown on every number</li>
<li>no named score without a human-signed task</li>
</ul>
</header>
${sections || `<p class="section-note">No run artifacts yet — the standings publish themselves from <code>lab-results.json</code> files.</p>`}
<footer class="meta">Every number on this page traces to a run artifact in <code>docs/verification/</code>. Methodology ${esc(METHODOLOGY_VERSION)} · generated by <code>@rosterhq/league</code> — static, zero backend, fork and rerun.</footer>`;

  return layout("ROSTER · The League — MCP server standings", body);
}

export function renderBoxScore(entry: StandingsEntry, taskDescriptions: ReadonlyMap<string, string>): string {
  const { run, artifact } = entry;
  const lb = displayLb(run);
  const eligible = run.summary.signedN > 0;
  const rows = run.results
    .map((r, i) => {
      const desc = taskDescriptions.get(r.taskId);
      return `<tr>
<td class="rk num">${i + 1}</td>
<td class="taskname">${esc(r.taskId)}${desc ? `<span class="taskdesc">${esc(desc)}</span>` : ""}${r.detail ? `<span class="taskdesc">${esc(r.stage ?? "")}: ${esc(r.detail)}</span>` : ""}</td>
<td><span class="chip ${r.pass ? "win" : "loss"}">${r.pass ? "W" : "L"}</span></td>
<td class="num">${r.latencyMs} ms</td>
</tr>`;
    })
    .join("\n");

  const body = `<a class="back" href="index.html">← Standings</a>
<header class="scorehead">
<div class="teamline"><h1>${esc(run.server)}</h1><span class="suitechip">${esc(run.suite)} v${esc(run.suiteVersion)} · ${esc(run.category)} division · LAB tier</span></div>
<div class="statrow">
<div class="stat"><div class="v">${record(run)}</div><div class="k">Record</div><div class="sub">${run.summary.passes} of ${run.summary.n} tasks</div></div>
<div class="stat"><div class="v">${fmt3(lb.value)}${lb.unsigned ? "<sup>U</sup>" : ""}</div><div class="k">Wilson LB</div><div class="sub">${lb.unsigned ? "all tasks (unsigned tier)" : "human-signed tasks only"}</div></div>
<div class="stat"><div class="v">${run.summary.signedN}/${run.summary.n}</div><div class="k">Signed</div><div class="sub">named-score eligible: ${eligible ? "yes" : "no"}</div></div>
</div>
${isPreSeason(run) ? `<div class="provenance">PRE-SEASON · UNSIGNED RUN — internal/anonymized tier. This page may not back a named public ranking until its tasks are human-signed (methodology §4).</div>` : ""}
</header>
<section class="division">
<div class="divhead"><h2>Box score</h2><span class="tierchip">END-STATE VERIFIED · NO LLM JUDGE</span></div>
<div class="tablewrap">
<table class="tasks">
<thead><tr><th>#</th><th>Task</th><th>Result</th><th>Latency</th></tr></thead>
<tbody>
${rows}
</tbody>
</table>
</div>
</section>
<section class="repro">
<h3>Reproduce this run</h3>
<pre>roster combine run suites/${esc(run.category)}/tasks.yaml --name ${esc(run.server)} \\
  -- &lt;server command&gt;   # {{sandbox}} in args is replaced per task</pre>
</section>
<footer class="meta">Run ${esc(artifact.data.generatedAt)} · node ${esc(artifact.data.environment.node)} · ${esc(artifact.data.environment.platform)}/${esc(artifact.data.environment.arch)} · environment digest <code title="${esc(artifact.data.environmentDigest)}">${esc(artifact.data.environmentDigest.slice(0, 12))}…</code> · methodology ${esc(METHODOLOGY_VERSION)} · artifact <code>${esc(artifact.path)}</code></footer>`;

  return layout(`${run.server} — box score · The League`, body);
}
